### ISSUE TITLE
Impose a 60 requests/ 60 sec limits for osu! Commands

### ISSUE THREAD

**Issue by sr229** [ClaraIO/Clara#37]
![image](https://cloud.githubusercontent.com/assets/14976516/22202182/e92c2734-e1a1-11e6-8093-cde0788e66c4.png)

**Comment by Ovyerus** [comment]
Will add in next version (0.3.0) with rewrite of command handler to use as an opportunity to clean up code in the process.

**Comment by sr229** [comment]
>0.3.0
>already released
ovypls
